### ISSUE TITLE
Plot size K31

### ISSUE THREAD

**Issue by romeo88vn** [madMAx43v3r/chia-plotter#889] opened 2021-08-08 04:04 UTC
can you make another version or integrate it into the next version for plot size k31?
Thanks!

**Comment by altendky** [comment] 2021-08-08 14:21
Duplicate of https://github.com/madMAx43v3r/chia-plotter/discussions/892.

**Comment by madMAx43v3r** [comment] 2021-08-23 10:54
It's done, see `-k`.

**Closed by madMAx43v3r** 2021-08-23 10:54 UTC
